services:
  db:
    image: "postgres:18"
    container_name: "prolepsis-db"
    restart: unless-stopped
    volumes:
      - prolepsis_db:/var/lib/postgresql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      PGUSER: "${PGUSER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - path: ".env"
        required: false
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 10s
      retries: 3
  rust-sidecar:
    build:
      context: .
      dockerfile: rust/Dockerfile.rust
    container_name: "prolepsis-rust-sidecar"
    restart: unless-stopped
    environment:
      GRPC_PDF_ADDRESS: ${GRPC_PDF_ADDRESS}
    ports:
      - 127.0.0.1:8081:8081
    env_file:
      - path: ".env"
        required: false

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: "prolepsis-backend"
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - prolepsis_backend:/var/log/mimi
    env_file:
      - path: ".env"
        required: false
    depends_on:
      db:
        condition: service_healthy
      rust-sidecar:
        condition: service_started

volumes:
  prolepsis_db:
  prolepsis_backend:
