FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

# Since we coppied everything from our local machine (at least the project), we will simply create a binary in the folder '/app/bin/<binary>' from '/app/cmd/mimi'
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/prolepsis ./cmd/mimi

FROM alpine:3.20

COPY --from=builder /app/bin/prolepsis ./
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN apk add --no-cache redis

EXPOSE 8080

CMD [ "./prolepsis" ]
