// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitHubMock = `-- name: DeleteGitHubMock :exec
TRUNCATE TABLE github_user, github_repo, github_repo_license
`

func (q *Queries) DeleteGitHubMock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteGitHubMock)
	return err
}

const insertGitHubLicenseInfo = `-- name: InsertGitHubLicenseInfo :exec
INSERT INTO github_repo_license(license_key, name, spdx_id, url, node_id)
VALUES(
    $1::text, $2::text, $3::text, $4::text, $5::text
)
`

type InsertGitHubLicenseInfoParams struct {
	LicenseKey string
	Name       string
	SpdxID     string
	Url        *string
	NodeID     string
}

func (q *Queries) InsertGitHubLicenseInfo(ctx context.Context, arg InsertGitHubLicenseInfoParams) error {
	_, err := q.db.Exec(ctx, insertGitHubLicenseInfo,
		arg.LicenseKey,
		arg.Name,
		arg.SpdxID,
		arg.Url,
		arg.NodeID,
	)
	return err
}

const insertGitHubRepoInfo = `-- name: InsertGitHubRepoInfo :exec
INSERT INTO github_repo (github_id, repo_id, name, html_url, description, created_at, pushed_at, stars, watches, forks_count, main_language, license_key, topic, archived, visibility)
VALUES(
    $1::bigint, $2::bigint, $3::text, $4::text, $5::text, $6::timestamptz, $7::timestamptz, $8::int, $9::int, $10::int, $11::text, $12::text, $13::text[], $14::boolean, $15::text
) ON CONFLICT (repo_id) DO UPDATE SET
name = EXCLUDED.name,
description = EXCLUDED.description,
pushed_at = EXCLUDED.pushed_at,
stars = EXCLUDED.stars,
watches = EXCLUDED.watches,
forks_count = EXCLUDED.forks_count,
main_language = EXCLUDED.main_language,
license_key = EXCLUDED.license_key,
topic = EXCLUDED.topic,
archived = EXCLUDED.archived,
visibility = EXCLUDED.visibility
`

type InsertGitHubRepoInfoParams struct {
	GithubID     int64
	RepoID       int64
	Name         string
	HtmlUrl      string
	Description  *string
	CreatedAt    pgtype.Timestamptz
	PushedAt     pgtype.Timestamptz
	Stars        *int32
	Watches      *int32
	ForksCount   *int32
	MainLanguage *string
	LicenseKey   *string
	Topic        []string
	Archived     bool
	Visibility   string
}

// We insert data inside the 'github_repo' table
func (q *Queries) InsertGitHubRepoInfo(ctx context.Context, arg InsertGitHubRepoInfoParams) error {
	_, err := q.db.Exec(ctx, insertGitHubRepoInfo,
		arg.GithubID,
		arg.RepoID,
		arg.Name,
		arg.HtmlUrl,
		arg.Description,
		arg.CreatedAt,
		arg.PushedAt,
		arg.Stars,
		arg.Watches,
		arg.ForksCount,
		arg.MainLanguage,
		arg.LicenseKey,
		arg.Topic,
		arg.Archived,
		arg.Visibility,
	)
	return err
}

const insertGitHubUserInfo = `-- name: InsertGitHubUserInfo :exec
INSERT INTO github_user (user_id, github_id, name, avatar_url, html_url, company, email, hireable, bio, followers, total_public_repos, total_private_repos, total_repos, created_at)
VALUES(
    $1::uuid, $2::bigint, $3::text, $4::text, $5::text, $6::text, $7::text, $8::boolean, $9::text, $10::int, $11::smallint, $12::smallint, $13::smallint, $14
) ON CONFLICT (github_id) DO UPDATE SET
name = EXCLUDED.name,
company = EXCLUDED.company,
email = EXCLUDED.email,
hireable = EXCLUDED.hireable,
bio = EXCLUDED.bio,
followers = EXCLUDED.followers,
total_public_repos = EXCLUDED.total_public_repos,
total_private_repos = EXCLUDED.total_private_repos,
total_repos = EXCLUDED.total_repos
`

type InsertGitHubUserInfoParams struct {
	UserID            pgtype.UUID
	GithubID          int64
	Name              string
	AvatarUrl         string
	HtmlUrl           string
	Company           *string
	Email             *string
	Hireable          *bool
	Bio               *string
	Followers         *int32
	TotalPublicRepos  int16
	TotalPrivateRepos int16
	TotalRepos        int16
	CreatedAt         pgtype.Timestamptz
}

// We use this to insert data about the user inside the 'github_user' table
func (q *Queries) InsertGitHubUserInfo(ctx context.Context, arg InsertGitHubUserInfoParams) error {
	_, err := q.db.Exec(ctx, insertGitHubUserInfo,
		arg.UserID,
		arg.GithubID,
		arg.Name,
		arg.AvatarUrl,
		arg.HtmlUrl,
		arg.Company,
		arg.Email,
		arg.Hireable,
		arg.Bio,
		arg.Followers,
		arg.TotalPublicRepos,
		arg.TotalPrivateRepos,
		arg.TotalRepos,
		arg.CreatedAt,
	)
	return err
}

const licenseExistsInsideGitHub = `-- name: LicenseExistsInsideGitHub :one
SELECT EXISTS (
    SELECT 1 FROM github_repo_license WHERE license_key = $1
)
`

func (q *Queries) LicenseExistsInsideGitHub(ctx context.Context, licenseKey string) (bool, error) {
	row := q.db.QueryRow(ctx, licenseExistsInsideGitHub, licenseKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const repoExistsInsideGitHub = `-- name: RepoExistsInsideGitHub :one
SELECT EXISTS (
    SELECT 1 FROM github_repo WHERE repo_id = $1
)
`

// We use this to check if there is already the same repository
func (q *Queries) RepoExistsInsideGitHub(ctx context.Context, repoID int64) (bool, error) {
	row := q.db.QueryRow(ctx, repoExistsInsideGitHub, repoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsInsideGitHub = `-- name: UserExistsInsideGitHub :one
SELECT EXISTS (
    SELECT 1 FROM github_user WHERE user_id = $1
)
`

// We use this to check if the oauth2 is already done (there is already a value)
func (q *Queries) UserExistsInsideGitHub(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsInsideGitHub, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
