// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kitanai.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session(token, created_at, expires_at)
VALUES ($1, now(), now() + interval '60 days')
`

// Simply insert the opaque token
func (q *Queries) CreateSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, createSession, token)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE token = $1
`

// We simply delete the session from users whose token is expired or when they log out
func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const emailForInfo = `-- name: EmailForInfo :one
SELECT id, name, email, password_hash
FROM users
WHERE email = $1
`

type EmailForInfoRow struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
}

// Use id from context (middleware) to fetch info in login (as the password to check if it matches)
func (q *Queries) EmailForInfo(ctx context.Context, email string) (EmailForInfoRow, error) {
	row := q.db.QueryRow(ctx, emailForInfo, email)
	var i EmailForInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const firstStepRegisterUser = `-- name: FirstStepRegisterUser :exec
INSERT INTO pending_registrations(token, name, display_name, gender, birth_date, email, password_hash, created_at, expires_at)
VALUES ($1::text, $2::text, $3::text, $4::text, $5::date, $6::text, $7::text, now(), now() + interval '5 minutes')
`

type FirstStepRegisterUserParams struct {
	Token        string
	Name         string
	DisplayName  string
	Gender       string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
}

// Temporarily inserting the user to 'pending_registrations' just to fetch the information later from it and register the user
func (q *Queries) FirstStepRegisterUser(ctx context.Context, arg FirstStepRegisterUserParams) error {
	_, err := q.db.Exec(ctx, firstStepRegisterUser,
		arg.Token,
		arg.Name,
		arg.DisplayName,
		arg.Gender,
		arg.BirthDate,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT name, display_name, bio, gender, location, birth_date, email, role, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	Name        string
	DisplayName *string
	Bio         *string
	Gender      string
	Location    *string
	BirthDate   pgtype.Date
	Email       string
	Role        UserRole
	CreatedAt   pgtype.Timestamptz
}

// An SQL code to fetch user information based on the given ID
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Bio,
		&i.Gender,
		&i.Location,
		&i.BirthDate,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const secondStepRegisterUser = `-- name: SecondStepRegisterUser :one
INSERT INTO users (name, display_name, gender, birth_date, email, password_hash, created_at)
VALUES ($1::text, $2::text, $3, $4::timestamptz, $5::text, $6::text, now())
RETURNING name, display_name, gender, birth_date, email, created_at
`

type SecondStepRegisterUserParams struct {
	Name         string
	DisplayName  string
	Gender       string
	BirthDate    pgtype.Timestamptz
	Email        string
	PasswordHash string
}

type SecondStepRegisterUserRow struct {
	Name        string
	DisplayName *string
	Gender      string
	BirthDate   pgtype.Date
	Email       string
	CreatedAt   pgtype.Timestamptz
}

// An SQL code to insert the users inside the database
func (q *Queries) SecondStepRegisterUser(ctx context.Context, arg SecondStepRegisterUserParams) (SecondStepRegisterUserRow, error) {
	row := q.db.QueryRow(ctx, secondStepRegisterUser,
		arg.Name,
		arg.DisplayName,
		arg.Gender,
		arg.BirthDate,
		arg.Email,
		arg.PasswordHash,
	)
	var i SecondStepRegisterUserRow
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Gender,
		&i.BirthDate,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE session
SET expires_at = now() + interval '60 days'
WHERE token = $1 AND expires_at > now() AND expires_at < now() + interval '30 days'
`

// We update the session if the user is active (we won't like to expire the session of an active user, no?)
// We update the token lifetime only if it's older than 30 days
func (q *Queries) UpdateSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, updateSession, token)
	return err
}

const updateUserNotForced = `-- name: UpdateUserNotForced :exec
UPDATE users
SET 
display_name = COALESCE($1::text, display_name),
bio = COALESCE($2::text, bio),
location = COALESCE($3::text, location)
WHERE id = $4::uuid
`

type UpdateUserNotForcedParams struct {
	DisplayName *string
	Bio         *string
	Location    *string
	ID          pgtype.UUID
}

// An SQL code to add info insdie the not-forced fields (display_name, bio, location)
// Update rows in 'TableName' where condition is met
// We get the id from the middleware!!!
func (q *Queries) UpdateUserNotForced(ctx context.Context, arg UpdateUserNotForcedParams) error {
	_, err := q.db.Exec(ctx, updateUserNotForced,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.ID,
	)
	return err
}
