// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUser   UserRole = "user"
	UserRoleAdmin  UserRole = "admin"
	UserRoleWorker UserRole = "worker"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type PendingRegistration struct {
	Token        string
	Name         string
	Gender       string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
	Attempts     int16
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type Session struct {
	UserID    pgtype.UUID
	Token     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	DisplayName  *string
	Bio          *string
	Gender       string
	Location     *string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
	Role         UserRole
	CreatedAt    pgtype.Timestamptz
}
