// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_deletions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeletionRequest = `-- name: InsertDeletionRequest :one
INSERT INTO pending_deletions (user_id, requested_by, clarification, requested_at, scheduled_at, is_processed)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    now(),
    now() + interval '24 hours',
    false
) RETURNING user_id, requested_by, clarification, requested_at, scheduled_at, is_processed
`

type InsertDeletionRequestParams struct {
	UserID        pgtype.UUID
	RequestedBy   pgtype.UUID
	Clarification string
}

// We store the request to delete a user inside the database
func (q *Queries) InsertDeletionRequest(ctx context.Context, arg InsertDeletionRequestParams) (PendingDeletion, error) {
	row := q.db.QueryRow(ctx, insertDeletionRequest, arg.UserID, arg.RequestedBy, arg.Clarification)
	var i PendingDeletion
	err := row.Scan(
		&i.UserID,
		&i.RequestedBy,
		&i.Clarification,
		&i.RequestedAt,
		&i.ScheduledAt,
		&i.IsProcessed,
	)
	return i, err
}

const updateIsProcessedField = `-- name: UpdateIsProcessedField :exec
UPDATE pending_deletions
SET is_processed = true
WHERE id = $1::uuid
`

// We gotta say who got deleted, no?
func (q *Queries) UpdateIsProcessedField(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateIsProcessedField, userID)
	return err
}
