// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_deletions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserByRequest = `-- name: DeleteUserByRequest :exec
DELETE FROM users
WHERE id = (
    SELECT id FROM pending_deletions WHERE id = $1::uuid AND is_processed = false
)
`

// We delete away the user
func (q *Queries) DeleteUserByRequest(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByRequest, userID)
	return err
}

const insertDeletionRequest = `-- name: InsertDeletionRequest :exec
INSERT INTO pending_deletions (user_id, requested_by, clarification, requested_at, is_processed)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    now(),
    false
)
`

type InsertDeletionRequestParams struct {
	UserID        pgtype.UUID
	RequestedBy   pgtype.UUID
	Clarification string
}

// We store the request to delete a user inside the database
func (q *Queries) InsertDeletionRequest(ctx context.Context, arg InsertDeletionRequestParams) error {
	_, err := q.db.Exec(ctx, insertDeletionRequest, arg.UserID, arg.RequestedBy, arg.Clarification)
	return err
}
