// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_registrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRegistrationSteps = `-- name: DeleteRegistrationSteps :exec
DELETE FROM pending_registrations
WHERE token = $1
`

// We delete everything, cuz yes
func (q *Queries) DeleteRegistrationSteps(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRegistrationSteps, token)
	return err
}

const deleteWhereDone = `-- name: DeleteWhereDone :exec
DELETE FROM pending_registrations
WHERE status = 'created' OR now() > expires_at
`

// We delete everything if the given status is 'created' or the token is 'expired'
func (q *Queries) DeleteWhereDone(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteWhereDone)
	return err
}

const fetchPendingRegistrationsInfo = `-- name: FetchPendingRegistrationsInfo :one
SELECT token, name, sex, birth_date, email, password_hash, created_at, expires_at
FROM pending_registrations
WHERE token = $1 AND expires_at > now()
`

type FetchPendingRegistrationsInfoRow struct {
	Token        string
	Name         string
	Sex          string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

// We fetch the info, so we can insert it later inside "users"
func (q *Queries) FetchPendingRegistrationsInfo(ctx context.Context, token string) (FetchPendingRegistrationsInfoRow, error) {
	row := q.db.QueryRow(ctx, fetchPendingRegistrationsInfo, token)
	var i FetchPendingRegistrationsInfoRow
	err := row.Scan(
		&i.Token,
		&i.Name,
		&i.Sex,
		&i.BirthDate,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const firstStepRegisterUser = `-- name: FirstStepRegisterUser :exec
INSERT INTO pending_registrations(token, name, sex, birth_date, email, password_hash, created_at, expires_at)
VALUES ($1::text, $2::text, $3::text, $4::date, $5::text, $6::text, now(), now() + interval '3 minutes')
`

type FirstStepRegisterUserParams struct {
	Token        string
	Name         string
	Sex          string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
}

// Temporarily inserting the user to 'pending_registrations' just to fetch the information later from it and register the user
func (q *Queries) FirstStepRegisterUser(ctx context.Context, arg FirstStepRegisterUserParams) error {
	_, err := q.db.Exec(ctx, firstStepRegisterUser,
		arg.Token,
		arg.Name,
		arg.Sex,
		arg.BirthDate,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const updatePendingStatus = `-- name: UpdatePendingStatus :exec
UPDATE pending_registrations
SET status  = 'created'
WHERE token = $1
`

// We update the status and fluff after creation
func (q *Queries) UpdatePendingStatus(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, updatePendingStatus, token)
	return err
}
