// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sent_emails.sql

package db

import (
	"context"
)

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM sent_emails
    WHERE to_email = $1 AND expires_at > now()
)
`

// We check if somebody already sent a mail to that email, if yes, we won't send any more
func (q *Queries) EmailExists(ctx context.Context, toEmail string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, toEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEmailCooldown = `-- name: InsertEmailCooldown :exec
INSERT INTO sent_emails (to_email, sent_at, expires_at)
VALUES ($1, now(), now() + interval '20 hours') ON CONFLICT (to_email) DO UPDATE
SET sent_at = EXCLUDED.sent_at, expires_at = EXCLUDED.expires_at
`

// We save the one to who we sent the email, so we place a timeout - so nobody will flood other's email for no reason
func (q *Queries) InsertEmailCooldown(ctx context.Context, toEmail string) error {
	_, err := q.db.Exec(ctx, insertEmailCooldown, toEmail)
	return err
}
