// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkToken = `-- name: CheckToken :one
SELECT users.id, users.role
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token = $1 AND sessions.expires_at > now()
`

type CheckTokenRow struct {
	ID   pgtype.UUID
	Role UserRole
}

// We use the token to fetch the info about the user
func (q *Queries) CheckToken(ctx context.Context, token string) (CheckTokenRow, error) {
	row := q.db.QueryRow(ctx, checkToken, token)
	var i CheckTokenRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(user_id, token, created_at, expires_at)
VALUES ($1, $2, now(), now() + interval '60 days')
`

type CreateSessionParams struct {
	UserID pgtype.UUID
	Token  string
}

// Simply insert the opaque token
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.Token)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

// We simply delete the sessions from users whose token is expired or when they log out
func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET expires_at = now() + interval '60 days'
WHERE token = $1 AND expires_at > now() AND expires_at < now() + interval '30 days'
`

// We update the sessions if the user is active (we won't like to expire the sessions of an active user, no?)
// We update the token lifetime only if it's older than 30 days
func (q *Queries) UpdateSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, updateSession, token)
	return err
}
