// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test.sql

package db

import (
	"context"
)

const insertDummiesInsideUsers = `-- name: InsertDummiesInsideUsers :exec

INSERT INTO users (id, name, sex, birth_date, email, password_hash, role)
VALUES
('00000000-0000-0000-0000-000000000001', 'Mimi Kagari', 'female', '2012-12-03', 'mimi@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'owner'),
('00000000-0000-0000-0000-000000000002', 'Sheena Totsuki', 'female', '2012-11-14', 'sheena@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000003', 'Ari Maud', 'female', '2012-05-01', 'ari@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000004', 'Seiran Lizzy', 'female', '2012-04-07', 'lizzy@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000005', 'Airi Sezaki', 'female', '2004-07-20', 'airi@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000006', 'Hinako Hanamura', 'female', '2004-11-24', 'hinako@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'owner'),
('00000000-0000-0000-0000-000000000007', 'Ichika Miyazono', 'female', '2003-04-12', 'ichika@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000008', 'Yoshimi Matsushita', 'female', '2004-07-20', 'yoshimi@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000009', 'Asya Shubina', 'female', '2008-05-14', 'asya@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000010', 'Vadim Garin', 'male', '2008-02-19', 'vadim@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000011', 'Tosya Lev', 'male', '2008-11-03', 'tosya@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000012', 'Ira Grachevskaya', 'female', '2008-09-17', 'ira@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000013', 'Marina Kaplan', 'female', '2008-07-28', 'marina@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000014', 'Leon Scott Kennedy', 'male', '1977-01-26', 'leon@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'worker'),
('00000000-0000-0000-0000-000000000015', 'Ethan Winters', 'male', '1984-02-10', 'ethan@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'worker'),
('00000000-0000-0000-0000-000000000016', 'Chris Redfield', 'male', '1973-08-22', 'chris@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'admin'),
('00000000-0000-0000-0000-000000000017', 'Jill Valentine', 'female', '1975-02-14', 'jill@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000018', 'Hakurei Reimu', 'female', '1997-08-15', 'reimu@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000019', 'Marisa Kirisame', 'female', '1997-08-15', 'marisa@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000020', 'Sakuya Izayoi', 'female', '2002-08-11', 'sakuya@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000021', 'Sanae Kochiya', 'female', '2007-08-17', 'sanae@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000022', 'Kurumi Yoshizawa', 'female', '2008-10-15', 'kurumi@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000023', 'Naoi Manaka', 'female', '2008-06-02', 'naoi@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user'),
('00000000-0000-0000-0000-000000000024', 'Loki Laufeyson', 'male', '1981-2-09', 'loki@test.com', '$2a$10$vRjMiLCoVTOLyUrj0k6K..J5McX9CTka2ab0vRgorpeWk.3OJE7mK', 'user')
`

// Generated with the help of AI (like...obviously, who will spend their time for something THIS boring) - but some minor fixes were implemented by me (as wrong birth_dates and little bugs)
// Random note -> Some birt dates were invented, since the author didn't know it too
// We simply inser random users (from different fandoms and stuff) inside the database, only for the test
func (q *Queries) InsertDummiesInsideUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertDummiesInsideUsers)
	return err
}

const truncateEverythingBeforeTest = `-- name: TruncateEverythingBeforeTest :exec
TRUNCATE TABLE users CASCADE
`

// We delete the data from users and sessions
func (q *Queries) TruncateEverythingBeforeTest(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateEverythingBeforeTest)
	return err
}
