// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const emailForInfo = `-- name: EmailForInfo :one
SELECT id, name, email, password_hash
FROM users
WHERE email = $1
`

type EmailForInfoRow struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
}

// We simply get info for later (inside login) - so we can update the session
func (q *Queries) EmailForInfo(ctx context.Context, email string) (EmailForInfoRow, error) {
	row := q.db.QueryRow(ctx, emailForInfo, email)
	var i EmailForInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT name, display_name, bio, sex, location, birth_date, email, role, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	Name        string
	DisplayName *string
	Bio         *string
	Sex         string
	Location    *string
	BirthDate   pgtype.Date
	Email       string
	Role        UserRole
	CreatedAt   pgtype.Timestamptz
}

// An SQL code to fetch user information based on the given ID
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Bio,
		&i.Sex,
		&i.Location,
		&i.BirthDate,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const secondStepRegisterUser = `-- name: SecondStepRegisterUser :one
INSERT INTO users (name, display_name, sex, birth_date, email, password_hash, created_at)
VALUES ($1::text, $2::text, $3, $4::date, $5::text, $6::text, now())
RETURNING id, name, display_name, sex, birth_date, email, created_at
`

type SecondStepRegisterUserParams struct {
	Name         string
	DisplayName  string
	Sex          string
	BirthDate    pgtype.Date
	Email        string
	PasswordHash string
}

type SecondStepRegisterUserRow struct {
	ID          pgtype.UUID
	Name        string
	DisplayName *string
	Sex         string
	BirthDate   pgtype.Date
	Email       string
	CreatedAt   pgtype.Timestamptz
}

// An SQL code to insert the users inside the database
func (q *Queries) SecondStepRegisterUser(ctx context.Context, arg SecondStepRegisterUserParams) (SecondStepRegisterUserRow, error) {
	row := q.db.QueryRow(ctx, secondStepRegisterUser,
		arg.Name,
		arg.DisplayName,
		arg.Sex,
		arg.BirthDate,
		arg.Email,
		arg.PasswordHash,
	)
	var i SecondStepRegisterUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Sex,
		&i.BirthDate,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserNotForced = `-- name: UpdateUserNotForced :exec
UPDATE users
SET 
display_name = COALESCE($1::text, display_name),
bio = COALESCE($2::text, bio),
location = COALESCE($3::text, location)
WHERE id = $4::uuid
`

type UpdateUserNotForcedParams struct {
	DisplayName *string
	Bio         *string
	Location    *string
	ID          pgtype.UUID
}

// An SQL code to add info insdie the not-forced fields (display_name, bio, location)
// We get the id from the middleware!!!
func (q *Queries) UpdateUserNotForced(ctx context.Context, arg UpdateUserNotForcedParams) error {
	_, err := q.db.Exec(ctx, updateUserNotForced,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.ID,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1 
)
`

// We also check if the user exists in the database with the same email before registering
func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
