// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pdf_grpc.proto

package pdf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "prolepsis/internal/pb/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *common.RequestContext `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	RawPdf        []byte                 `protobuf:"bytes,2,opt,name=raw_pdf,json=rawPdf,proto3" json:"raw_pdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfRequest) Reset() {
	*x = PdfRequest{}
	mi := &file_pdf_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfRequest) ProtoMessage() {}

func (x *PdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdf_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfRequest.ProtoReflect.Descriptor instead.
func (*PdfRequest) Descriptor() ([]byte, []int) {
	return file_pdf_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *PdfRequest) GetCtx() *common.RequestContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *PdfRequest) GetRawPdf() []byte {
	if x != nil {
		return x.RawPdf
	}
	return nil
}

type PdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfTitle      string                 `protobuf:"bytes,1,opt,name=pdf_title,json=pdfTitle,proto3" json:"pdf_title,omitempty"`
	PdfContent    string                 `protobuf:"bytes,2,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfResponse) Reset() {
	*x = PdfResponse{}
	mi := &file_pdf_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfResponse) ProtoMessage() {}

func (x *PdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdf_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfResponse.ProtoReflect.Descriptor instead.
func (*PdfResponse) Descriptor() ([]byte, []int) {
	return file_pdf_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *PdfResponse) GetPdfTitle() string {
	if x != nil {
		return x.PdfTitle
	}
	return ""
}

func (x *PdfResponse) GetPdfContent() string {
	if x != nil {
		return x.PdfContent
	}
	return ""
}

var File_pdf_grpc_proto protoreflect.FileDescriptor

const file_pdf_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0epdf_grpc.proto\x12\x03pdf\x1a\fcommon.proto\"O\n" +
	"\n" +
	"PdfRequest\x12(\n" +
	"\x03ctx\x18\x01 \x01(\v2\x16.common.RequestContextR\x03ctx\x12\x17\n" +
	"\araw_pdf\x18\x02 \x01(\fR\x06rawPdf\"K\n" +
	"\vPdfResponse\x12\x1b\n" +
	"\tpdf_title\x18\x01 \x01(\tR\bpdfTitle\x12\x1f\n" +
	"\vpdf_content\x18\x02 \x01(\tR\n" +
	"pdfContent29\n" +
	"\n" +
	"PdfService\x12+\n" +
	"\x06PdfRPC\x12\x0f.pdf.PdfRequest\x1a\x10.pdf.PdfResponseB\x1bZ\x19prolepsis/internal/pb/pdfb\x06proto3"

var (
	file_pdf_grpc_proto_rawDescOnce sync.Once
	file_pdf_grpc_proto_rawDescData []byte
)

func file_pdf_grpc_proto_rawDescGZIP() []byte {
	file_pdf_grpc_proto_rawDescOnce.Do(func() {
		file_pdf_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdf_grpc_proto_rawDesc), len(file_pdf_grpc_proto_rawDesc)))
	})
	return file_pdf_grpc_proto_rawDescData
}

var file_pdf_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pdf_grpc_proto_goTypes = []any{
	(*PdfRequest)(nil),            // 0: pdf.PdfRequest
	(*PdfResponse)(nil),           // 1: pdf.PdfResponse
	(*common.RequestContext)(nil), // 2: common.RequestContext
}
var file_pdf_grpc_proto_depIdxs = []int32{
	2, // 0: pdf.PdfRequest.ctx:type_name -> common.RequestContext
	0, // 1: pdf.PdfService.PdfRPC:input_type -> pdf.PdfRequest
	1, // 2: pdf.PdfService.PdfRPC:output_type -> pdf.PdfResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pdf_grpc_proto_init() }
func file_pdf_grpc_proto_init() {
	if File_pdf_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdf_grpc_proto_rawDesc), len(file_pdf_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdf_grpc_proto_goTypes,
		DependencyIndexes: file_pdf_grpc_proto_depIdxs,
		MessageInfos:      file_pdf_grpc_proto_msgTypes,
	}.Build()
	File_pdf_grpc_proto = out.File
	file_pdf_grpc_proto_goTypes = nil
	file_pdf_grpc_proto_depIdxs = nil
}
