// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pdf_grpc.proto

package pdf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfService_PdfRPC_FullMethodName = "/pdf.PdfService/PdfRPC"
)

// PdfServiceClient is the client API for PdfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Here we precise how the function is going to be like, it must accept as request the structure of PdfRequest (RequestContext and raw_pdf) and it must send back (as Response) the structure of PdfResponse (pdf_title and pdf_content
// Summary: Go sends the request (structure of PdfRequest) and responds with the structure of PdfResponse
type PdfServiceClient interface {
	PdfRPC(ctx context.Context, in *PdfRequest, opts ...grpc.CallOption) (*PdfResponse, error)
}

type pdfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfServiceClient(cc grpc.ClientConnInterface) PdfServiceClient {
	return &pdfServiceClient{cc}
}

func (c *pdfServiceClient) PdfRPC(ctx context.Context, in *PdfRequest, opts ...grpc.CallOption) (*PdfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PdfResponse)
	err := c.cc.Invoke(ctx, PdfService_PdfRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfServiceServer is the server API for PdfService service.
// All implementations must embed UnimplementedPdfServiceServer
// for forward compatibility.
//
// Here we precise how the function is going to be like, it must accept as request the structure of PdfRequest (RequestContext and raw_pdf) and it must send back (as Response) the structure of PdfResponse (pdf_title and pdf_content
// Summary: Go sends the request (structure of PdfRequest) and responds with the structure of PdfResponse
type PdfServiceServer interface {
	PdfRPC(context.Context, *PdfRequest) (*PdfResponse, error)
	mustEmbedUnimplementedPdfServiceServer()
}

// UnimplementedPdfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfServiceServer struct{}

func (UnimplementedPdfServiceServer) PdfRPC(context.Context, *PdfRequest) (*PdfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PdfRPC not implemented")
}
func (UnimplementedPdfServiceServer) mustEmbedUnimplementedPdfServiceServer() {}
func (UnimplementedPdfServiceServer) testEmbeddedByValue()                    {}

// UnsafePdfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfServiceServer will
// result in compilation errors.
type UnsafePdfServiceServer interface {
	mustEmbedUnimplementedPdfServiceServer()
}

func RegisterPdfServiceServer(s grpc.ServiceRegistrar, srv PdfServiceServer) {
	// If the following call panics, it indicates UnimplementedPdfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfService_ServiceDesc, srv)
}

func _PdfService_PdfRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).PdfRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_PdfRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).PdfRPC(ctx, req.(*PdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfService_ServiceDesc is the grpc.ServiceDesc for PdfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdf.PdfService",
	HandlerType: (*PdfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PdfRPC",
			Handler:    _PdfService_PdfRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdf_grpc.proto",
}
