[package]
name = "prolepsis-sidecar"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.104"
pdf_oxide = "0.3.78"
prost = "0.14.4"
protoc = "2.28.0"
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }

[build-dependencies]
anyhow = "1.0.104"
prost-build = "0.12"
tonic-prost-build = "0.14.6"

[[bin]]
name = "prolepsis"
path = "src/bin/main.rs"